# CI -Pipeline

# This YAML configuration is for a GitHub Actions workflow named "Check Build."
# GitHub Actions is a tool for automating software workflows, such as testing, building, and deploying code.

name: Check Build

on:
#on any push event on main branch we run this workflowl;
  push:
    branches:
      - main
#on any PR to main branch we run this workflow
  pull_request:
    branches:
      - main

# you do not need to manually install Node.js on the GitHub Actions runner. 
#GitHub Actions provides pre-configured virtual environments (runners) like ubuntu-latest, 
# which already include popular tools and languages, including Node.js.

#actions* is a set of actions provided by GitHub to perform common tasks.

jobs:
  # This workflow contains a single job called "chack-build"
  check-build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v3
      
      # This action allows you to specify the version of Node.js you want to use
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'

      # Install Node.js
      - name: Install
        run: npm install
      # Build the project
      - name: Build
        run: npm run build

