# CI -Pipeline

# This YAML configuration is for a GitHub Actions workflow named "Check Build."
# GitHub Actions is a tool for automating software workflows, such as testing, building, and deploying code.

name: Check Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# you do not need to manually install Node.js on the GitHub Actions runner. 
#GitHub Actions provides pre-configured virtual environments (runners) like ubuntu-latest, 
# which already include popular tools and languages, including Node.js.

jobs:
  # This workflow contains a single job called "chack-build"
  chack-build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v3
      # Install Node.js
      - name: Install
        run: npm install
      # Build the project
      - name: Build
        run: npm run build

