name: Build and Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          # Username and password are set as secrets in the githuub repository
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          # your username and name of repo on dockerhub
          tags: deepanshu2711/node-app:latest
      # don't really need it
      # - name: Verify Pushed Image
      #   run: docker image inspect deepanshu2711/node-app:latest

      #Creare a EC2 instance and install docker inside it

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          #pull the latest docker image
          #stop the running container
          #remove the container
          #start new  container
          script: |
            whoami
            groups
            sudo docker pull deepanshu2711/node-app:latest
            sudo docker stop node-app || true
            sudo docker rm node-app || true
            sudo docker run -d -p 3000:3000 --name node-app deepanshu2711/node-app:latest

